services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:tFonTdgm+DIWsZ0WH2317SPPsA6aHicFOgN37j70Q78=
      - key: APP_URL
        value: https://deploytest-a8wi.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: FILESYSTEM_DISK
        value: local
      - key: SESSION_DRIVER
        value: database
      - key: VITE_APP_NAME
        value: Laravel
